# Generated by Django 3.2.15 on 2022-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='myblog', max_length=200),
        ),
    ]
