# Generated by Django 3.2.15 on 2022-09-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_type',
            field=models.CharField(choices=[('Poem', 'Poem'), ('Book Review', 'Book Review'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
    ]
